exports.insultos = [
    'Hablando de madres: ¿es verdad que la tuya es tan gorda que tiene su propio código postal?',
    '¿Sabes?, yo podría haber sido tu padre, pero el tipo que estaba a mi lado tenía el dinero exacto',
    'Come-albóndigas',
    'Perroflauta',
    'Eres la versión antropomórfica de la Comic Sans',
    'Cara de limón podrído',
    'Eres más pesado que matar a un cerdo a besos',
    'Tienes halitosis…pero si lo supieras no hablarías tanto',
    'Tu mujer debe disfrutar cada vez que juegas. Más que nada porque por unas horas no tiene que aguantarte.',
    '¿Alguien te dijo alguna vez que eres una persona increíblemente promedio?',
    '¿Te das cuenta de que la gente solo te tolera?',
    'Deberías tratar de comer un poco de maquillaje para ser más bella por dentro.',
    'Disculpa pero tengo cosas mejores con las que perder el tiempo.',
    'Eres tan brillante como un agujero negro y el doble de denso.',
    'No tengo una respuesta apropiada para alguien de tu edad mental.',
    'Espero que el resto de tu día sea tan agradable como tú.',
    'Hay 7 trillones de nervios en el cuerpo humano, y tú irritas todos.',
    'La envidia es una enfermedad. Espero que te mejores.',
    'La gente feliz no tiene necesidad de amargar a los demás.',
    'Lástima que no puedas usar Photoshop en tu personalidad.',
    'Me asombra ver cómo le pones tanto entusiasmo a algo tan obvio.',
    'Me encanta cómo dices cosas obvias con la sensación de que descubriste algo.',
    'Me niego a pelear con un oponente desarmado.',
    'Mirar a alguien con impaciencia y decir: ¿Ya terminaste?',
    'No se qué cualidades puedes tener que compensen esa actitud que tienes.',
    'Puedo explicártelo pero no puedo entenderlo por ti.',
    'Que tengas un buen día, en cualquier otro lugar.',
    'Siento decirte que jamás pedí tu opinión. Gracias.',
    'Te devuelvo tu nariz. Se había metido en mis asuntos.',
    'Todas las personas que te amaron alguna vez estaban equivocados.',
    'Todo el mundo puede ser estúpido alguna vez, pero tú abusas del privilegio.',
    'Tu singular punto de vista nos ha dejado perplejo.',
    'Ya que lo sabes todo, sabrás cuándo callarte.',
    '¡Fuera! Eres veneno para mi sangre.',
    '¿Cuál es el parentesco entre tus padres?',
    'De no ser por la risa debería tenerte lastima.',
    'Jamás has usado una palabra que obligue a alguien a buscar un diccionario.',
    'Los asnos están hechos para cargar y, tu también.',
    'Me arrepiento de los tediosos minutos que he pasado contigo.',
    'No hay nada malo en ti que la reencarnación no pueda arreglar.',
    'No iré a tu funeral, pero enviaré una bonita carta aprobándolo.',
    'No tiene enemigos, pero es intensamente aborrecido por todos sus amigos.',
    'Tienes todas las virtudes que odio y ninguno de los vicios que admiro.',
    'Tu rostro es como febrero, lleno de escarcha, tormentas y nubosidad.'
];

