exports.piropos = [
    'Quien fuera caramelo para poder derretirse en tu boca.',
    'Mi amor, tengo la caja fuerte para guardar ese lingote de oro.',
    '¿Y si nos comemos unos tacos y yo te a-taco a besos?',
    'Algún día Tom se comerá a Jerry, Silvestre a Piolín y yo a ti.',
    'No tengas miedo… sí que muerdo, pero muy suave.',
    'Quiero olvidarte, pero sin el “olvi”.',
    'Ni bañándome se me quitó todo lo sucio que quiero hacerte.',
    '¿Por qué en vez de un beso de buenas noches no me das una noche de buenos besos?',
    '¡Me encanta tu camisa! Creo que combinaría a la perfección con mis sábanas...',
    'Si yo fuera un avión y tú mi aeropuerto aterrizaría todos los días en tu exquisito cuerpo.',
    'Ojalá fueras sol y me dieras todo el día.',
    'Quisiera ser patata frita para acompañar ese lomo.',
    'Si fueras salsa, estaría mojando todo el día.',
    'Conmigo nunca te va a faltar amor. Y si te falta, lo hacemos…',
    'Tu ropa me da miedo. ¿Puedes quitártela?',
    'Dime como te llamas y así lograré ponerle un nombre a mis sueños',
    'Como mejor está ese cuerpo es sin ropa que lo adorne.',
    '¡Cuidado! Estás entrando en zona obligatoria de besos.',
    'Eres como la zapatilla de mi madre. Te veo venir y se me acelera el corazón.',
    'Ni en clase de matemáticas me pierdo tanto como en tu mirada...',
    'Estás como Paco… Paco-merte a besos.',
    'Mándame tu ubicación que quiero saber dónde está mi tesoro.',
    '¡Quién fuera paloma para posarme en esa rama!',
    'Ya tengo el Netflix, sólo me faltas tú a mi lado. Y date prisa, que sólo es el mes de prueba.',
    'Por darte un bocado me salto yo la dieta.',
    'Si vas a estar en mi cabeza todo el día, al menos ponte algo de ropa...',
    'Contigo me pasaría cien años en cuarentena.',
    'Ojalá te roben la cama y te vengas a dormir conmigo.',
    '¡Ya quisiera la Guardia Civil tener ese cuerpo!',
    'No sé si eres Bill Gates, pero pareces muy rico.',
    'Dicen que no hay hombre bueno, pero quiero descubrir si tú eres la excepción.',
    'Si estar bueno es un pecado, no tienes perdón de Dios.',
    'Si te gustan las alegrías, aquí tengo yo una para tu cuerpo.',
    'No seré agricultor, pero si me dejas te planto unos besos.',
    'Entre nosotros hay más química que en toda la tabla periódica.',
    '¡Quién fuera cinturón para recorrer esa cintura!',
    'Si supieras cuánto pienso en ti me denunciarías por acoso mental.',
    'Cómo le gustaría a mi madre que tú fueses su nuera...',
    'Quién fuera zapatero para trabajar ese cuero.',
    '¿No te da claustrofobia pasar todo el día en mi cabeza?',
    '¡Qué perrito más mono! ¿Tiene número de teléfono?',
    'Adán se comió la manzana, pero yo por ti me comería la frutería entera...',
    'Si fuera alcalde te hacía una plaza en mitad del pueblo.',
    'El amor será ciego, pero hay que ver lo que alegras la vista...',
    'Qué bonitos son los días de viento para faldas como esa.',
    '¡Cuéntame qué comes para estar tan buena!',
    'Me gusta mucho una persona, pero no te voy a decir quién es.',
    'Tarjeta amarilla por la falta que me haces.',
    'Lo mejor de ti es todo lo que te hace tan tú.',
    'Tienes algo pegado en el culo… ¡Mi mirada!',
    'Ni la miopía me impide ver lo guapa que eres.',
    'Si una amiga es un tesoro, tú eres una mina de oro.',
    '¡Con amigas como tú, quién necesita novio!',
    'Tú no necesitas que te dé el sol, tú brillas con luz propia.',
    'Por ti, mato un elefante a chancletazos.',
    'Aparte de la comida, tú eres lo que más me gusta.',
    'Sólo estoy a gusto cuando estoy contigo. Eres el pantalón del pijama de mi vida.',
    '¿Sabes por lo que estoy agradecida hoy? Por ser amigas. Y por la Nutella.',
    'No es fácil ser yo. Por eso te necesito a ti, amiga.',
    '¿Sabes lo que es increíble? Un pastel de chocolate... ¡ah, y tú tampoco estás mal!',
    'La parte más difícil de ser amigos es fingir que mis otros amigos me gustan tanto como tú.',
    'El amor será ciego, pero hay que ver lo mucho que alegras la vista.',
    'Con esos ojos mirándome, ya no me hace falta la luz del sol.',
    'Por la luna daría un beso, daría todo por el sol, pero por la luz de tu mirada, doy mi vida y corazón.',
    'Si yo fuera un avión y tu un aeropuerto, me la pasaría aterrizando por tu hermoso cuerpo.',
    'Me gusta el café, pero prefiero tener-té.',
    'No eres google, pero tienes todo lo que yo busco.',
    'Mis ganas de ti no se quitan, se acumulan.',
    'Cuando te multen por exceso de belleza, yo pagaré tu fianza.',
    'Si cada gota de agua sobre tu cuerpo es un beso, entonces quiero convertirme en aguacero.',
    'Estas como para invitarte a dormir, y no dormir.',
    'Si tu cuerpo fuera cárcel y tus brazos cadenas, ese sería el lugar perfecto para cumplir condena.',
    'Qué bonitos ojos tienes, tan redondos como el sol, se parecen a los ceros que me pone el profesor.'
];